create table medical_history(
  id int primary key  generated by default as identity not null,
  admitted_id timestamp, 
  patient_id int references patients(id),
  status VARCHAR
);

create table patients(
  id int primary generated by default as identity key not null,
  name varchar(20),
  date_of_birth date
);

create table invoice(
  id int primary key generated by default as identity not null,
  total_amout decimal,
  generated_at timestamp,
  payed_at timestamp,
  medical_history_id int references medical_history(id)
);












/*task a
# command for creating medical histories table
- many to one relationship with patients
- one to one relationship with invoices

# command for creating patients table
- one to many relationship with medical histories

# command for creating invoices table
- one to one relationship with medical histories
- one to many relationship with invoice iterms

task B
# command for creating invoice_items table
- many to one relationship with invoices
- many to one relationship with treatments

# command for creating treatments table
- many to many relationship with medical histories
- on to many relationship with invoice_items

# command for creating many to many relationship table between treatments and medical records*/