create table medical_history(
  id int primary key  generated by default as identity not null,
  admitted_id timestamp, 
  patient_id int references patients(id),
  status VARCHAR
);

create table patients(
  id int primary generated by default as identity key not null,
  name varchar(20),
  date_of_birth date
);

create table invoice(
  id int primary key generated by default as identity not null,
  total_amout decimal,
  generated_at timestamp,
  payed_at timestamp,
  medical_history_id int references medical_history(id)
);

CREATE TABLE invoice_items (
id INT GENERATED ALWAYS AS IDENTITY,
unit_price DECIMAL,
quantity INT,
total_price DECIMAL,
invoice_id INT NOT NULL,
treatment_id INT NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE,
FOREIGN KEY (treatment_id) REFERENCES treatments(id) ON DELETE CASCADE
);


CREATE TABLE treatments (
id INT GENERATED ALWAYS AS IDENTITY,
type VARCHAR,
name VARCHAR,
PRIMARY KEY (id),
);

CREATE TABLE treatments_medical_histories (
id INT GENERATED ALWAYS AS IDENTITY,
PRIMARY KEY (id),
medical_histories_id INT NOT NULL,
treatment_id INT NOT NULL,
FOREIGN KEY(medical_histories_id) REFERENCES medical_histories(id) ON DELETE CASCADE,
FOREIGN KEY(treatment_id) REFERENCES treatments(id) ON DELETE CASCADE,
);
